/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/profile01.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Level.geometry} material={materials.Level} position={[-0.38, 0.69, 0.62]} rotation={[Math.PI / 2, -Math.PI / 9, 0]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-0.01, 1.52, -0.92]} rotation={[Math.PI / 2, 0, 0]} scale={[0.54, 1, 0.29]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[-0.32, 1.59, -0.88]} rotation={[Math.PI / 2, 0, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/profile01.glb')
